[package]
name = "tin_can_telephone"
version = "0.1.0"
authors = ["kibbles <colindjk@gmail.com>"]

[dependencies]
serde = "0.8.*"
serde_xml = "0.8.*"
serde_derive = "0.8.*"

futures = "0.1"
tokio-core = "0.1"

env_logger = "0.3"
